server:
  port: 8082

spring:
  servlet:
    multipart:
      max-file-size: "12MB"
      max-request-size: "12MB"
  datasource:
    url: "jdbc:postgresql://pwcDb:5432/compose-postgres?stringtype=unspecified&useUnicode=true&characterEncoding=UTF-8"
    username: "compose-postgres"
    password: "compose-postgres"
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
    url: "jdbc:postgresql://pwcDb:5432/compose-postgres?stringtype=unspecified"
    user: "compose-postgres"
    password: "compose-postgres"
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        jdbc:
          batch_size: "30"
        order_inserts: "true"
        order_updates: "true"
        show_sql: false
        temp:
          use_jdbc_metadata_defaults: false
        dialect: org.hibernate.dialect.PostgreSQLDialect
