CREATE TABLE IF NOT EXISTS "actions" (
	"id" BIGINT NOT NULL,
	"userId" BIGINT NOT NULL,
	"topicId" BIGINT NOT NULL,
	"seen" BOOLEAN NOT NULL DEFAULT 'false',
	"like" BOOLEAN NOT NULL DEFAULT 'false',
	PRIMARY KEY ("id"),
	CONSTRAINT "FK_actions_topics" FOREIGN KEY ("topicId") REFERENCES "public"."topics" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION,
	CONSTRAINT "FK_actions_users" FOREIGN KEY ("userId") REFERENCES "public"."users" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION
);